cmake_minimum_required(VERSION 3.20)
project(LeetCode_Solutions)

set(CMAKE_CXX_STANDARD 17)

add_executable(two_sum "Easy/0001-Two-Sum/solution.cpp")
add_executable(palindrome_number "Easy/0009-Palindrome-Number/solution.cpp")
add_executable(roman_to_integer "Easy/0013-Roman-to-Integer/solution.cpp")
add_executable(longest_common_prefix "Easy/0014-Longest-Common-Prefix/solution.cpp")
add_executable(valid_parentheses "Easy/0020-Valid-Parentheses/solution.cpp")
add_executable(merge_two_sorted_lists "Easy/0021-Merge-Two-Sorted-Lists/solution.cpp")
add_executable(remove_duplicates_from_sorted_array "Easy/0026-Remove-Duplicates-from-Sorted-Array/solution.cpp")
add_executable(remove_elements "Easy/0027-Remove-Elemente/solution.cpp")
add_executable(find_the-index_of_the_first_occurence_in_the_string "Easy/0028-Find-The-Index-Of-The-First-Occurence-In-The-String./solution.cpp")
add_executable(search_insert_position "Easy/0035-Search-Insert-Position./solution.cpp")
add_executable(length_of_last_word "Easy/0058-Length-of-Last-Word./solution.cpp")
add_executable(plus_one "Easy/0066-Plus-One./solution.cpp")
add_executable(add-binary "Easy/0067-Add-Binary/solution.cpp")
add_executable(sqrt "Easy/0069-sqrt/solution.cpp")
add_executable(climbing_stairs "Easy/0070-Climbing-Stairs/solution.cpp")
add_executable(remove_duplicates_from_sorted_list "Easy/0083-Remove-Duplicates-from-Sorted-List/solution.cpp")
add_executable(merge_sorted_array "Easy/0088-Merge-Sorted-Array/solution.cpp")
add_executable(binary_tree_inorder_traversal "Easy/0094-Binary-Tree-Inorder-Traversal/solution.cpp")
add_executable(same_tree "Easy/0100-Same-Tree/solution.cpp")
add_executable(symmetric_tree "Easy/0101-Symmetric-Tree/solution.cpp")
add_executable(maximum_depth_of_binary_tree "Easy/0104-Maximum-Depth-of-Binary-tree/solution.cpp")
add_executable(convert_sorrarr_to_binary "Easy/0108-Convert-SorrArr-to-Binary/solution.cpp")
add_executable(balanced_binary_tree "Easy/0110-Balanced-Binary-Tree/solution.cpp")
add_executable(minimum_depth_of_binary_tree "Easy/0111-Minimum-Depth-of-Binary-Tree/solution.cpp")
add_executable(path_sum "Easy/0112-Path-Sum/solution.cpp")
add_executable(pascal's triangle "Easy/0118-Pascal's-Triangle/solution.cpp")
add_executable(pascal's triangle II "Easy/0119-Pascal's-Triangle-II/solution.cpp")
add_executable(best_time_to_buy_and_sell_stock "Easy/0121-Best-Time-To-Buy-and-Sell-Stock/solution.cpp")
add_executable(valid_palindrome "Easy/0125-Valid-Palindrome/solution.cpp")
add_executable(single_number "Easy/0136-Single-Number/solution.cpp")
add_executable(linked_list_cycle "Easy/0141-Linked-List-Cycle/solution.cpp")
add_executable(binary_tree_preorder_traversal "Easy/0144-Binary-Tree-Preorder-Traversal/solution.cpp")
add_executable(intersection_of_two_linked_lists "Easy/0160-Intersection-of-Two-Linked-Lists/solution.cpp")
add_executable(excel_sheet_column_title "Easy/0168-Excel-Sheet-Column-Title/solution.cpp")
add_executable(majority_element "Easy/0169-Majority-Element/solution.cpp")
add_executable(excel_sheet_column_number "Easy/0171-Excel-Sheet-Column-Number/solution.cpp")
add_executable(reverse_bits "Easy/0190-Reverse-Bits/solution.cpp")
add_executable(happy_number "Easy/0202-Happy-Number/solution.cpp")
add_executable(remove_linked_list_elements "Easy/0203-Remove-Linked-List-Elements/solution.cpp")
add_executable(isomorphic_strings "Easy/0205-Isomorphic-Strings/solution.cpp")
add_executable(reversed_linked_list "Easy/0206-Reverse-Linked-List/solution.cpp")


